name: sfdx_test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate with Salesforce
        run: sf org login --client-id ${{ secrets.SFDX_CLIENT_ID }} --set-default-dev-hub --alias my-hub-org
