name: sfdx_test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate with Salesforce
        run: sf org login web --client-id ${{ secrets.SFDX_CLIENT_ID }} --set-default-dev-hub --alias my-hub-org -v ${{ secrets.SFDX_USERNAME }}
        
      - name: Create a new scratch org
        run: sf org create scratch --edition developer --no-namespace --duration-days 30 -v ${{ secrets.SFDX_USERNAME }}

      - name: Push code to scratch org
        run: sf force:source:push -u scratch-org -v ${{ secrets.SFDX_USERNAME }}
      
      - name: Run tests
        run: sf force:apex:test:run -u scratch-org -c -w 10 -r human -v ${{ secrets.SFDX_USERNAME }}
      
      - name: Create a log file
        run: sf force:apex:test:run -u scratch-org --json > test-results.json -v ${{ secrets.SFDX_USERNAME }}
      
      - name: Display test results
        run: cat test-results.json
      
      - name: Delete the scratch org
        run: sf force:org:delete -u scratch-org -p -v ${{ secrets.SFDX_USERNAME }}
