name: sfdx_test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli
        
      - name: Authenticate with Salesforce Dev Hub
        run: |
          sfdx auth:web:login --instance-url https://login.salesforce.com --set-alias my-dev-hub --set-default-dev-hub --client-id ${{ secrets.SFDX_CLIENT_ID }}

      - name: Authenticate with Salesforce
        run: |
          sfdx auth:web:login --instance-url https://login.salesforce.com --set-alias my-hub-org --set-default --client-id ${{ secrets.SFDX_CLIENT_ID }}

      - name: Create Scratch Org
        run: |
          sfdx force:org:create -d 30 -a my-scratch-org -f config/project-scratch-def.json -v ${{ secrets.SFDX_USERNAME }}

      - name: Push source code to Scratch Org
        run: sfdx force:source:push -u my-scratch-org

      - name: Run tests
        id: run-tests
        run: |
          result=$(sfdx force:apex:test:run -u my-scratch-org --outputdir test-results --resultformat human)
          echo "::set-output name=test-run-id::$(echo $result | grep -oP '(?<=\bTestId\b.*?\b).*(?=\b\])')"

      - name: Create log file
        run: sfdx force:apex:test:report -i ${{ steps.run-tests.outputs.test-run-id }} -u my-scratch-org --resultformat human > test-results/test-log.txt

      - name: Show test results
        run: cat test-results/test-log.txt
