name: sfdx_test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Write JWT key file
        run: echo "${{ secrets.JWT }}" > jwt.key

      - name: Authenticate with Salesforce
        run: sf org login jwt --username ${{ secrets.SFDX_USERNAME }} --client-id ${{ secrets.SFDX_CLIENT_ID }} --jwt-key-file jwt.key

      - name: Remove JWT key file
        run: rm jwt.key
